# Generated by Django 3.2.8 on 2021-10-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_trade_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
