# Generated by Django 3.2.8 on 2021-10-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_trade_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
