# Generated by Django 3.2.8 on 2021-10-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_trade_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='trade',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='crypto',
            name='marketplace',
            field=models.ManyToManyField(to='main_app.Marketplace'),
        ),
    ]
